params:
  batch_size: 24
  epochs: 150
  iters_per_epoch: 375 
  print_every: 100 # show train loss at every n steps 
  valid_every: 100

dataset_params:
  name: kalapa_finetune_with_empty # dataset name (choose whatever name you want, this name tells trainner that this data is already exists or not, if not, create it (lmdb format))
  data_root: /workplace/datasets/ # rootdir (path to folder contains data)
  train_annotation: labels_train_gt.txt # path to train annotation (inside rootdir)
  valid_annotation: labels_val_gt.txt # path to valid annotation (inside rootdir)
  image_height: 48
  image_min_width: 48
  image_max_width: 960

dataloader:
    num_workers: 6
    pin_memory: True

seed: 0
model: seq2seq # transformer or seq2seq
backbone: vgg11_bn
vocab: 0123456789aàảãáạăằẳẵắặâầẩẫấậbcdđeèẻẽéẹêềểễếệfghiìỉĩíịjklmnoòỏõóọôồổỗốộơờởỡớợpqrstuùủũúụưừửữứựvwxyỳỷỹýỵzAÀẢÃÁẠĂẰẲẴẮẶÂẦẨẪẤẬBCDĐEÈẺẼÉẸÊỀỂỄẾỆFGHIÌỈĨÍỊJKLMNOÒỎÕÓỌÔỒỔỖỐỘƠỜỞỠỚỢPQRSTUÙỦŨÚỤƯỪỬỮỨỰVWXYỲỶỸÝỴZ !"#$%&'()*+,-./:;<=>?@[\]_`~
save_path: ./output/kalapa_vgg11_finetune/checkpoints/ # Leave this field blank, the default will be checkpoints/vietocr/${now:%Y-%m-%d}_${now:%H-%M-%S}/
